name: CI 

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore healthmed.sln

      - name: Compilar a aplicação
        run: dotnet build HealthMed.Api/HealthMed.Api.csproj --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test HealthMed.Tests/HealthMed.Tests.csproj --configuration Release

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME_IMAGE}}/healthmed-api:latest -f HealthMed.Api/Dockerfile .

      - name: Publicar imagem no Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME_IMAGE}}/healthmed-api
